// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23GivPQE826iP06DnQvZGuafvcHwrR1A',
    appId: '1:909447691315:web:c3394e7d3473738743b746',
    messagingSenderId: '431146169809',
    projectId: 'the-hafleh-app',
    authDomain: 'the-hafleh-app.firebaseapp.com',
    storageBucket: 'the-hafleh-app.appspot.com',
    measurementId: 'G-KKL6FZWV3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHv9WEoY8g5bJ36whd_BY3CK7_5Au_rQ',
    appId: '1:431146169809:android:dae9116da3a98b13171cf0',
    messagingSenderId: '431146169809',
    projectId: 'the-hafleh-app',
    storageBucket: 'the-hafleh-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXd7eMEKEn5xY2uPgT_2cbGuDUL9uQvQ',
    appId: '1:431146169809:ios:be8d43ef18bf7df4171cf0',
    messagingSenderId: '431146169809',
    projectId: 'the-hafleh-app',
    storageBucket: 'the-hafleh-app.appspot.com',
    androidClientId: '',
    iosClientId:
        '431146169809-jru47dub72fcgo3u4qlgpm6ik21vrc8v.apps.googleusercontent.com',
    iosBundleId: 'app.hafleh',
  );
}
